---
deployment:
  tasks:
    - /bin/mkdir -p /home2/saifulsh/.saifulshuvo-deploy/logs
    - /bin/touch /home2/saifulsh/.saifulshuvo-deploy/cpanel-runner.log
    - /bin/bash /home2/saifulsh/repositories/saifulshuvo/scripts/cpanel-build-deploy.sh >> /home2/saifulsh/.saifulshuvo-deploy/cpanel-runner.log 2>&1
